### PR TITLE
Change css modules to BEM and update example application

### LINKED ISSUE #159: unable to style ListItem component
I have an webpage where the background is a gradient. I can't seem to be able to remove the white background and the flex properties from the listitem wrapper without having to built the css file from scratch. Not sure if I'm doing something wrong.

.content {
  width: 100%;
  align-items: center;
  box-sizing: border-box;
  background-color: #fff;
  height: 100%;
  display: flex;
}

Screenshot of issue
https://prnt.sc/seic00

### PR DESCRIPTION
**Pull request by marekrozmus**
Closes #159

### CODE REVIEW

File: examples/src/App.js [hunk 1]
```diff
@@ -64,10 +62,16 @@ class App extends PureComponent {
     const { selectedExample } = this.state;
 
     return (
-      <div className={styles.example}>
-        <h1>react-swipeable-list example</h1>
-        <h5>(try also mobile view in dev tools for touch events)</h5>
-        <select value={selectedExample} onChange={this.handleSelectExample}>
+      <div className="page-content">
+        <div className="page-content__title">react-swipeable-list example</div>
```
Comment (przemyslawzalewski) [inline examples/src/App.js:66]: Please keep semantic tags for better indexability and accessibility. At least the title (h1).

File: examples/src/complex/ComplexExample.js [hunk 2]
```diff
@@ -5,13 +5,12 @@ import {
 } from '@sandstreamdev/react-swipeable-list';
 import '@sandstreamdev/react-swipeable-list/dist/styles.css';
 
-import ListItem from './ListItem';
-import ItemContent from './ItemContent';
+import ComplexListItem from '../list-items/ComplexListItem';
+import ComplexSwipeContent from '../list-items/ComplexSwipeContent';
 import { MailIcon, ReplyIcon, DeleteIcon } from '../../images/icons';
+import './ComplexExample.css';
```
Comment (przemyslawzalewski) [inline examples/src/complex/ComplexExample.js:11]: Consider spacing out the side-effectful imports.

```suggestion

import './ComplexExample.css';
```

File: examples/src/styled/StyledExample.js [hunk 3]
```diff
@@ -26,38 +20,30 @@ const StyledList = () => {
...
   return (
     <>
-      <span className={styles.actionInfo}>Custom styled list wrapper</span>
-      <div className={styles.listContainer}>
+      <span className="page__action--title">Custom styled list wrapper</span>
+      <div className="styled-swipeable-list__container">
         <SwipeableList>
           {({ className, ...rest }) => (
-            <div className={classNames(className, customStyles.customList)}>
+            <div className={`${className} styled-swipeable-list`}>
```
Comment (przemyslawzalewski) [inline examples/src/styled/StyledExample.js:38]: This will have negative effect when className is `undefined` or `null` -> the helper handles these cases gracefully.

File: examples/src/App.css [hunk 4]
```diff
@@ -1,37 +1,23 @@
...
 
-h1,
-h2,
-h3,
-h4,
-h5 {
-  margin-left: 16px;
-  margin-right: 16px;
+.page-content__title {
+  font-size: 19px;
```
Comment (przemyslawzalewski) [inline examples/src/App.css:9]: Consider using some "round" value for font-size and margin-top, eg. `20px` and `16px`.

File: examples/src/animations/AnimationsExample.css [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+
+.animations__switcher-row {
+  padding-top: 8px;
+}
+
+.my-node-exit {
+  opacity: 1;
+}
+
+.my-node-exit-active {
```
Comment (przemyslawzalewski) [inline examples/src/animations/AnimationsExample.css:21]: Can the `-active` modifier be made into a proper BEM modifier `--active`?

File: examples/src/animations/AnimationsExample.js [hunk 6]
```diff
@@ -9,16 +9,11 @@ import {
 import '@sandstreamdev/react-swipeable-list/dist/styles.css';
 import { findKey, mapEntries } from '@sandstreamdev/std/object';
 
-import styles from '../app.module.css';
-import transitionStyles from './transitions.module.css';
+import BasicListItem from '../list-items/BasicListItem';
+import BasicSwipeContent from '../list-items/BasicSwipeContent';
+import './AnimationsExample.css';
```
Comment (przemyslawzalewski) [inline examples/src/animations/AnimationsExample.js:14]: Consider spacing out imports with side effects.

File: examples/src/basic/BasicExample.js [hunk 7]
```diff
@@ -5,37 +5,25 @@ import {
 } from '@sandstreamdev/react-swipeable-list';
 import '@sandstreamdev/react-swipeable-list/dist/styles.css';
 
-import styles from '../app.module.css';
+import BasicListItem from '../list-items/BasicListItem';
+import BasicSwipeContent from '../list-items/BasicSwipeContent';
+import './BasicExample.css';
```
Comment (przemyslawzalewski) [inline examples/src/basic/BasicExample.js:10]: Please see my comments about spacing imports with side effects.

File: examples/src/basic/BasicExample.js [hunk 8]
```diff
@@ -74,23 +62,23 @@ const SimpleList = () => {
             onSwipeProgress={handleSwipeProgress}
             onSwipeStart={handleSwipeStart}
           >
-            {itemContent('Item with both swipes')}
+            <BasicListItem label="Item with both swipes" />{' '}
```
Comment (przemyslawzalewski) [inline examples/src/basic/BasicExample.js:65]:
```suggestion
            <BasicListItem label="Item with both swipes" />
```

File: examples/src/complex/ComplexExample.js [hunk 9]
```diff
@@ -24,23 +23,21 @@ const ComplexList = () => {
 
   const swipeRightOptions = name => ({
     content: (
-      <ItemContent
-        color="red"
+      <ComplexSwipeContent
+        direction="left"
```
Comment (przemyslawzalewski) [inline examples/src/complex/ComplexExample.js:27]: Were the directions swapped intentionally? Now the direction is left and the element is named right. Please investigate.

File: examples/src/complex/ComplexExample.js [hunk 10]
```diff
@@ -24,23 +23,21 @@ const ComplexList = () => {
...
     ),
     action: () => triggerItemAction(`Delete action triggered on "${name}" item`)
   });
 
   const swipeLeftOptions = name => ({
     content: (
-      <ItemContent
-        color="green"
+      <ComplexSwipeContent
+        direction="right"
```
Comment (przemyslawzalewski) [inline examples/src/complex/ComplexExample.js:38]: :up:

File: examples/src/index.js [hunk 11]
```diff
@@ -1,31 +1,39 @@
...
+      <div className="smartfone__content">
         <App />
       </div>
     </div>
-    <footer>
+    <footer className="footer smartfone__footer">
       <span>
         {`Made with ❤️ by `}
-        <a href="https://sanddev.com/">Sandstream Development</a>
+        <a className="footer__link" href="https://sanddev.com/">
```
Comment (przemyslawzalewski) [inline examples/src/index.js:17]: Consider making the target="_blank" with proper rels (noopener, noref).

File: examples/src/list-items/ComplexListItem.css [hunk 12]
```diff
@@ -8,12 +8,12 @@
   cursor: pointer;
 }
 
-.label {
+.complex-swipeable-list__item--label {
```
Comment (przemyslawzalewski) [inline examples/src/list-items/ComplexListItem.css:11]: Shouldn't all these be just `elements` of the list item instead of BEM modifiers?

File: examples/src/list-items/ComplexSwipeContent.css [hunk 13]
```diff
@@ -21,9 +29,10 @@
   max-width: 64px;
   text-align: center;
   padding: 4px;
+  padding-top: 8px;
 }
 
-svg {
+.complex-swipeable-list__svg {
```
Comment (przemyslawzalewski) [inline examples/src/list-items/ComplexSwipeContent.css:35]: Please make the class more semantic, e.g. icon instead of an element type.

File: examples/src/size-to-content/SizeToContentExample.js [hunk 14]
```diff
@@ -6,13 +6,12 @@ import {
 import '@sandstreamdev/react-swipeable-list/dist/styles.css';
 import { noOp } from '@sandstreamdev/std/function';
 
-import ListItem from '../complex/ListItem';
-import ItemContent from '../complex/ItemContent';
+import ComplexListItem from '../list-items/ComplexListItem';
+import ComplexSwipeContent from '../list-items/ComplexSwipeContent';
 import { MailIcon, ReplyIcon, DeleteIcon } from '../../images/icons';
+import './SizeToContentExample.css';
```
Comment (przemyslawzalewski) [inline examples/src/size-to-content/SizeToContentExample.js:12]: Please see my comments about spacing imports with side effects.

File: examples/src/styled/StyledExample.js [hunk 15]
```diff
@@ -5,19 +5,13 @@ import {
...
 } from '@sandstreamdev/react-swipeable-list';
 import '@sandstreamdev/react-swipeable-list/dist/styles.css';
-import { classNames } from '@sandstreamdev/std/web';
 import { noOp } from '@sandstreamdev/std/function';
 
-import styles from '../app.module.css';
-import customStyles from './custom.module.css';
+import BasicListItem from '../list-items/BasicListItem';
+import BasicSwipeContent from '../list-items/BasicSwipeContent';
+import './StyledExample.css';
```
Comment (przemyslawzalewski) [inline examples/src/styled/StyledExample.js:12]: Please see my comments about spacing imports with side effects.

File: examples/src/styled/StyledExample.js [hunk 16]
```diff
@@ -26,38 +20,30 @@ const StyledList = () => {
   ];
 
   const swipeRightOptions = () => ({
-    content: (
-      <div className={styles.contentLeft}>
-        <span>Delete</span>
-      </div>
-    ),
+    content: <BasicSwipeContent direction="left" label="Delete" />,
```
Comment (przemyslawzalewski) [inline examples/src/styled/StyledExample.js:23]: Right/left mismatch. Please investigate.

File: src/SwipeableListItem.js [hunk 17]
```diff
@@ -106,13 +106,13 @@ class SwipeableListItem extends PureComponent {
     this.resetState();
     this.dragStartPoint = { x: clientX, y: clientY };
 
-    this.listElement.className = styles.content;
+    this.listElement.className = 'swipeable-list-item__content';
```
Comment (przemyslawzalewski) [inline src/SwipeableListItem.js:109]:
```suggestion
    this.listElement.className = 'swipeable-list-item__content';

```

File: examples/src/animations/AnimationsExample.css (hunk 5 above)
Comment (marekrozmus) [reply examples/src/animations/AnimationsExample.css:21]: Nope. Please check http://reactcommunity.org/react-transition-group/css-transition

File: examples/src/complex/ComplexExample.js (hunk 9 above)
Comment (marekrozmus) [reply examples/src/complex/ComplexExample.js:27]: this is position of content on revealed content - changed name to `position`

File: examples/src/animations/AnimationsExample.css (hunk 5 above)
Comment (przemyslawzalewski) [reply examples/src/animations/AnimationsExample.css:21]: Seems to be doable with http://reactcommunity.org/react-transition-group/css-transition#CSSTransition-prop-classNames

> Each individual classNames can also be specified independently like:
> 
> classNames={{
>  appear: 'my-appear',
>  appearActive: 'my-active-appear',
>  appearDone: 'my-done-appear',
>  enter: 'my-enter',
>  enterActive: 'my-active-enter',
>  enterDone: 'my-done-enter',
>  exit: 'my-exit',
>  exitActive: 'my-active-exit',
>  exitDone: 'my-done-exit',
> }}
